Ios input handling improvements
ttristan/ts-body-scroll-lock pull request #3
Opened 2022-12-22 09:52 UTC by k-ruben

2022-12-22 11:59 UTC, ttristan requested changes

2022-12-22 11:59 UTC, ttristan commented on src/lib.ts
> +  if (!element) {
With an `instanceof` Check here you can prevent the Type Cast in line 209 and be sure it is what we expect it to be

2022-12-22 11:59 UTC, ttristan commented on src/lib.ts
> +  return getElement('html') as HTMLHtmlElement;
Type Casts of this kind should not be necessary since getElement should already make sure the right type is returned

2022-12-22 11:59 UTC, ttristan commented on src/lib.ts
> +      const scrollContentElement = entries[0].target.parentElement;
```suggestion
      const scrollContentElement = entries[0]?.target.parentElement;
```

2022-12-30 12:32 UTC, ttristan approved these changes

2022-12-30 12:32 UTC, merged

2023-08-31 03:06 UTC, Ckeahbotros commented on src/lib.ts
> +      const scrollContentElement = entries[0].target.parentElement;
209?